- GenAIEval/evaluation/bigcode_evaluation_harness/__init__.py
- GenAIEval/evaluation/bigcode_evaluation_harness/accuracy.py
- GenAIEval/evaluation/bigcode_evaluation_harness/arguments.py
- GenAIEval/evaluation/lm_evaluation_harness/__init__.py
- GenAIEval/evaluation/lm_evaluation_harness/accuracy.py
- GenAIEval/evaluation/lm_evaluation_harness/arguments.py
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/evaluator.py
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/models/__init__.py
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/models/huggingface.py
- README.md
- main.py
- requirements.txt
- tests/test_bigcode_eval.py
- tests/test_lm_eval.py
There is a small code change in `main.py` regarding the import path.
```diff
- from GenAIEval.evaluation.lm_evaluation_harness import evaluate, setup_parser
+ from GenAIEval.evaluation.bigcode_evaluation_harness import evaluate, setup_parser
```
```shell
python main.py \
--model "codeparrot/codeparrot-small" \
--tasks "humaneval" \
--n_samples 100 \
--batch_size 10 \
--allow_code_execution \
```
```python
from GenAIEval.evaluation.bigcode_evaluation_harness import evaluate, BigcodeEvalParser
args = BigcodeEvalParser(
user_model = user_model,
tokenizer = tokenizer,
tasks = "humaneval",
n_samples = 100,
batch_size = 10,
allow_code_execution=True,
)
results = evaluate(args)
```
> Add `bigcode-evaluation-harness` support

- .github/workflows/model_test_cpu.yml
- .github/workflows/model_test_hpu.yml
- .github/workflows/unittest.yml
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/models/huggingface.py
customize a GenAI_HFLM class to request GenAI microservice.
> add GenAI_HFLM class to support microservice.

- README.md
- setup.py
We have to install requirements.txt at first, cause Pypi can't have direct dependency with specific commit.
> update install bkc

- .github/workflows/model_test_cpu.yml
- .github/workflows/model_test_hpu.yml
- .github/workflows/scripts/install_evals.sh
- .github/workflows/scripts/unittest/calc_coverage.sh
- .github/workflows/scripts/unittest/unittest.sh
- .github/workflows/unittest.yml
- evals/evaluation/lm_evaluation_harness/accuracy.py
- evals/evaluation/lm_evaluation_harness/lm_eval/models/huggingface.py
- tests/test_lm_eval.py
The summary of the proposed changes as long as the relevant motivation and context.
> Fix coverage command

- evals/metrics/ragas/__init__.py
- evals/metrics/ragas/ragas.py
- tests/test_ragas.py
discussed with @XuhuiRen  @lkk12014402, metrics context_recall, context_precision have random issue, the issue also be raised in ragas, so remove these first.
https://github.com/explodinggradients/ragas/issues/664
https://github.com/explodinggradients/ragas/issues/934
usage:
```
metric = RagasMetric(threshold=0.5, model="http://10.45.76.150:8008", embeddings=embeddings, metics=["answer_relevancy", "faithfulness" ])
```
test_ragas.py local test results
```
(test) [changwa1@aia-sdp-spr-117706 tests]$ python test_ragas.py 
/home/changwa1/miniconda3/envs/test/lib/python3.10/site-packages/huggingface_hub-0.23.4-py3.10.egg/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want …
```
> improve ragas metrics random issue

- evals/evaluation/autorag/evaluation/README.md
add readme to introduce how to use the autorag service for evaluating the RAG services
> add readme for autorag

- evals/benchmark/stresscli/locust/chatqnabench.py
Fixe the chatqnabench benchmark script issue, that the query list id out-of-range sometimes
n/a
n/a
Tested on IDC gaudi cluster
> Fixed query list id out-of-range issue

- docker/hpu.dockerfile
- evals/evaluation/rag_eval/examples/eval_multihop.py
- evals/metrics/ragas/ragas.py
1. enhance multihop dataset accuracy
2. add rerank
3. add `answer_correctness](https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/_answer_correctness.py)` metric in ragas
> enhance multihop dataset accuracy

- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
Support service-list for metrics collection in benchmark.py.
#102 
- Bug fix (non-breaking change which fixes an issue)
N/A
Manual tests
> Support service-list for metrics collection in benchmark.py

- evals/evaluation/bigcode_evaluation_harness/api_evaluator.py
- examples/CodeGen/README.md
Add README for codegen acc test.
> Add README for codegen acc test.

- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/embeddingfixed.py
- evals/benchmark/stresscli/locust/embedservefixed.py
- evals/benchmark/stresscli/locust/rerankingfixed.py
- evals/benchmark/stresscli/locust/rerankservefixed.py
- evals/benchmark/stresscli/locust/retrieverfixed.py
- evals/benchmark/stresscli/locust/tokenresponse.py
Support microservice level benchmark
`n/a`.
None
Local test
> Support microservice level benchmark

- evals/benchmark/benchmark.yaml
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/commands/metrics.py
- evals/benchmark/stresscli/commands/metrics_docker.py
- evals/benchmark/stresscli/commands/metrics_util.py
- evals/benchmark/stresscli/requirements.txt
Add the support to collect service metrics for containers if OPEA AI workload is deployed with Docker.
> [v1.0] Add docker metric support

- requirements.txt
fix bigcode install issue by update version when python >= 3.11
https://github.com/opea-project/GenAIEval/issues/99
> fix bigcode version when python>=3.11

- evals/benchmark/auto_tuning/README.md
When you mark a code-block as JSON, it must follow JSON syntax or it throws a warning when the github.io documents are built.  I removed the invalid `...`.
> doc: fix JSON example

- evals/benchmark/stresscli/commands/load_test.py
add bench-target as the prefix of output folder, in order to easily understand the test case of the output
Currently, all output folders are in timestamp format. When testing with multiple endpoints, it's very hard to understand which test cases output folder is. Adding the bench-target can easily separate different test cases.
n/a
n/a
> add bench-target as the prefix of output folder

- LEGAL_INFORMATION.md
- README.md
- doc/platform-optimization/README.md
- evals/evaluation/agent_eval/crag_eval/README.md
Cross-repo references using an URL that only has the folder name cause links in the github.io site to go to the github.com site.  Most of these uses want to link to the documentation (README.md) so add that where appropriate so links in the github.io site stay there.
> doc: fix missing references to README.md

- evals/evaluation/rag_eval/examples/eval_crud.py
add ragas evaluation for crud Chinese dataset.
> add crud ragas evaluation.

- evals/benchmark/stresscli/locust/retrieverfixed.py
The getReqData function was incorrectly returning a tuple containing a dictionary, which is not a valid JSON format.
Fix JSON Return Format in getReqData Function
n/a
- [✓] Bug fix (non-breaking change which fixes an issue)
NA
Retriever benchmark now works with no failures:
===Starting test: benchmark                                                                                                                                                                                                       
Running test: locust --locustfile /home/ronglei/rag/GenAIEval/evals/benchmark/stresscli/locust/aistress.py --host http://10.112.120.165:7000 --run-time 60m --load-shape constant --processes 2 --users 1 --spawn-rate 1 …
> Fix JSON Return Format in getReqData Function

- evals/benchmark/benchmark.py
- evals/benchmark/utils.py
- evals/metrics/ragas/ragas.py
Patch for a small change required in ragas.py. 
`n/a`.
None
> Quick fix for ragas.py

- evals/benchmark/README.md
- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/constant_load_shape.py
- evals/benchmark/utils.py
- Fix the excessive request of poisson loader caused by Locust limitation
- Add a new constant loader as a custom load shape controlled by configured request arrival-rate
`n/a`
None
Local tests
> Add new constant loader & Fix poisson loader issue

- evals/benchmark/stresscli/locust/aistress.py
When the import error of bench target occurs, the GenAIEval hangs until the test wall time(60 mins by default) is reached. So we need to raise the error to abort the test with exceptions in time.
`n/a`.
> Raise the error if importing bench target fails.

- evals/evaluation/longbench/README.md
- evals/evaluation/longbench/pred.py
> Support Longbench 

- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/tokenresponse.py
Fix test duration time inaccurate issue
`n/a`
None
Local test.
> Fix test duration time inaccurate issue

- .github/workflows/docker/hpu.dockerfile
- .github/workflows/model_test_cpu.yml
- .github/workflows/model_test_hpu.yml
- docker/hpu.dockerfile
Update HPU Dockerfile to 1.18 
Fix CI path
`n/a`
`n/a`
`n/a`
> Update HPU Dockerfile to latest version and fix CI

- evals/benchmark/stresscli/locust/chatqnafixed.py
Fixed the output token in chatqnafixed.py.
N/A
N/A
> [ChatQnA Benchmark] Fixed the output token in chatqnafixed.py

- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/faqgenfixed.py
- evals/benchmark/stresscli/locust/tokenresponse.py
Fix the metrics parse and statistics for FaqGen benchmark:
* Switch from `json` to `data` param to send client request for FaqGen benchmark to fit the `FormData` input_type.
* Fix the input length statistics, to avoid negative numbers of `Input Tokens` and `Input Tokens per Second`.
* Fix the output length statistics by implementing the extraction of all generated texts from streaming output, to avoid extremely large values of `Output Tokens` and `Output Tokens per Second`. 
* Update the default input prompt and set Top K=1 in sampling for faqgen, as the original default prompt does not provide any valid details for faq generation. 
https://github.com/opea-project/GenAIEval/issues/189
n/a
Benchmark on …
> [FaqGen] Fix the metrics parse and statistics for benchmark

- evals/benchmark/stresscli/locust/chatqna_qlist_pubmed.py
- evals/benchmark/stresscli/locust/tokenresponse.py
1. modify respStatics function parameters
2. support chatqna_qlist_pubmed bench_target for input token calculation.
Benchmark of ChatQnA on pubmed dataset failed for wrong function parameters.
None
Local tested on k8s.
> Fix chatqna pubmed benchmark issues.

- evals/benchmark/stresscli/commands/load_test.py
The poisson_load_shape.py file was located using relative path, refined to absolute path now so that outer files can call this function correctly.
Found this issue in PR: https://github.com/opea-project/GenAIExamples/pull/1531
None
Local tested
> Fix relative path issue for possion.

- evals/benchmark/stresscli/locust/aistress.py
missing streaming config of chatqna_qlist_pubmed
Lack of the config will cause the error of "next token latency"
example
```
End to End latency(ms),    P50: 25875.62,   P90: 34988.45,   P99: 56357.57,   Avg: 26382.29
Time to First Token-TTFT(ms),   P50: 25875.21,   P90: 34987.96,   P99: 56357.17,   Avg: 26381.87
Time Per Output Token-TPOT(ms),   P50: 0.00,   P90: 0.00,   P99: 0.01,   Avg: 0.00
```
1. deploy the chatqna v1.2 
2. git pull the evel code
3.use locust command line to verify bench-target …
> fix the error  of TTFT and TPOT while the bench target is chatqna_qlist_pubmed

- evals/benchmark/stresscli/commands/metrics_util.py
This is to collect and calculate vllm latency metric in e2e test.
fix #245 
> Collect vllm latency metric for e2e test

- evals/benchmark/grafana/chatqna_megaservice_grafana.json
- evals/benchmark/grafana/cpu_grafana.json
- evals/benchmark/grafana/dataprep_microservice_grafana.json
- evals/benchmark/grafana/embedding_microservice_grafana.json
- evals/benchmark/grafana/gaudi_grafana.json
- evals/benchmark/grafana/qdrant_grafana.json
- evals/benchmark/grafana/redis_grafana.json
- evals/benchmark/grafana/rerank_microservice_grafana.json
- evals/benchmark/grafana/retrieval_microservice_grafana.json
- evals/benchmark/grafana/tei_grafana.json
Got issues to see Grafana Dashboard for mega and micro services.
it should be caused by changing UID among systems.
We fixed by removing UID dependency following the suggestion from below post.
https://community.grafana.com/t/should-provisioned-dashboards-have-datasource-uids/65463/8
all dashboards work now based on the merged PR : https://github.com/opea-project/GenAIExamples/pull/1623
[Issue#247](https://github.com/opea-project/GenAIEval/issues/247)
NA
Manually test
> Fix Grafana Dashboard datasource issue by removing uid dependency

- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/docsumbench.py
- evals/benchmark/stresscli/locust/docsumfixed.py
Added DocSum service as a part of stresscli
* Initial benchmarking support for DocSum
* Add parameters for summary_type support
* Add parameter for output streaming
* Added support for fixed testing and custom input testing
https://github.com/opea-project/GenAIEval/issues/240
- [x ] New feature (non-breaking change which adds new functionality)
n/a
Executed test run  with user provided file and default fixed input.
>  Added docsum service as a part of stresscli

- requirements.txt
Restrict numpy version to below 2.0 in requirements.txt
`n/a`.
CI
> Restrict numpy version to below 2.0 in requirements.txt

- evals/benchmark/benchmark.py
For each benchmark test case, save benchmark result in same folder.
n/a
> Organize the benchmark output folder

- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/tokenresponse.py
The previous logic implemented [[Reference](https://github.com/opea-project/GenAIEval/blob/21f618b612ce40e3f4ba174691b5aa1ed6ebfcb2/evals/benchmark/stresscli/locust/tokenresponse.py#L16C1-L50C1)] for calculating the number of input and output tokens for CodeGen, CodeTrans, and DocSum fails to provide the expected results:
- Input tokens were consistently reported as -1.
- Output tokens were overestimated due to parsing the entire response_string instead of focusing on the relevant parts
In the currently implemented code, the token count logic assumes an output format like:
```
data: b'The'  
data: b' provided'  
data: b' text'  
data: b' is'  
data: b' a'  
data: b' collection'  
```
However, for CodeGen, CodeTrans, and DocSum, the actual output format was different. For example, in …
> Fix for Input/Output Token Count Calculation for specific GenAIExamples
