- GenAIEval/evaluation/bigcode_evaluation_harness/accuracy.py
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/evaluator.py
- GenAIEval/evaluation/lm_evaluation_harness/lm_eval/models/huggingface.py
- README.md
- tests/test_bigcode_eval.py
use `isort` first and then use `black` to correct the format.
```
pip install isort black
git clone https://github.com/opea-project/GenAIEval.git
isort GenAIEval
black GenAIEval
```
> Fix format with `isort` and `black`

- GenAIEval/evaluation/bigcode_evaluation_harness/main.py
- GenAIEval/evaluation/lm_evaluation_harness/main.py
- README.md
feature or bug fix or documentation or validation or others
detail description
how to reproduce the test (including hardware information)
any library dependency introduced or removed
> Separate main.py to lm_eval and bigcode_eval

- tests/test_bigcode_eval.py
feature or bug fix or documentation or validation or others
detail description
how to reproduce the test (including hardware information)
any library dependency introduced or removed
> Reduce UT time

- .github/license_template.txt
- .github/pull_request_template.md
others
update PR and license template
> update PR and license template

- .github/workflows/docker/hpu.dockerfile
- .github/workflows/model_test.yml
- .github/workflows/model_test_cpu.yml
- .github/workflows/model_test_hpu.yml
- .github/workflows/scripts/models/collect_log.sh
- .github/workflows/scripts/models/generate_report.sh
- .github/workflows/scripts/models/model_test.sh
- Docker/hpu.dockerfile
refine model test by adding report and hpu test
> Add modeltest

- README.md
add lm-eval microservice usage.
> add lm-eval microservice usage.

- .github/workflows/docker/code-scan.dockerfile
- .github/workflows/docker/common.dockerfile
- .github/workflows/docker/hpu.dockerfile
- .github/workflows/model_test_cpu.yml
- Docker/hpu.dockerfile
- requirements.txt
- setup.py
to make `pip install -e .` has the same function with `pip install -r requirements.txt && python setup.py install`
- update docker setuptools version ==69.5.1, the latest 70.0.0 has something wrong. 
> Improve `setup.py` for installation

- LEGAL_INFORMATION.md
- README.md
Use common security content for OPEA projects
https://github.com/opea-project/GenAIExamples/issues/272
NA
NA
> Use common security content for OPEA projects

- evals/metrics/__init__.py
- evals/metrics/ragas/__init__.py
- evals/metrics/ragas/ragas.py
- evals/metrics/ragas/test_ragas.py
- requirements.txt
- tests/requirements.txt
- tests/test_ragas.py
the usage as "test_ragas.py" show.
> Add RAGASMetric

- evals/evaluation/bigcode_evaluation_harness/accuracy.py
- evals/evaluation/bigcode_evaluation_harness/arguments.py
- evals/evaluation/lm_evaluation_harness/accuracy.py
- evals/evaluation/lm_evaluation_harness/arguments.py
- evals/evaluation/lm_evaluation_harness/lm_eval/evaluator.py
- evals/evaluation/lm_evaluation_harness/lm_eval/models/huggingface.py
The summary of the proposed changes as long as the relevant motivation and context.
> Add CopyRight for lm-eval and bigcode-eval

- setup.py
> bump version into v0.7

- evals/evaluation/lm_evaluation_harness/accuracy.py
- evals/evaluation/lm_evaluation_harness/lm_eval/evaluator.py
- requirements.txt
- tests/requirements.txt
lm-eval update to 0.4.3 and adapt api.
`logging_utils` changed to `loggers.utils`
add `high_is_better` in metrics infos
> Update lm-eval to 0.4.3

- evals/metrics/bias/__init__.py
- evals/metrics/bias/bias.py
- evals/metrics/bias/schema.py
- evals/metrics/bias/template.py
- evals/metrics/hallucination/__init__.py
- evals/metrics/hallucination/hallucination.py
- evals/metrics/hallucination/schema.py
- evals/metrics/hallucination/template.py
- evals/metrics/toxicity/__init__.py
- evals/metrics/toxicity/schema.py
- evals/metrics/toxicity/template.py
- evals/metrics/toxicity/toxicity.py
- evals/metrics/utils.py
- tests/test_bias.py
- tests/test_hallucination.py
- tests/test_toxicity.py
add toxicity/bias/hallucination metrics.
> add toxicity/bias/hallucination metrics.

- evals/metrics/answer_relevancy/__init__.py
- evals/metrics/answer_relevancy/answer_relevancy.py
- evals/metrics/answer_relevancy/template.py
- evals/metrics/retrieval/__init__.py
- evals/metrics/retrieval/retrieval.py
- tests/test_answer_relevancy.py
- tests/test_retrieval_metric.py
add retrieval related metrics map/mrr/hit
add answer relevancy metrics wiht llm-as-judge
> add rag related metrics.

- requirements.txt
- tests/requirements.txt
Use the correct commit sha of bigcode-eval
closes #53 
n/a
n/a
> Use the correct commit sha of bigcode-eval

- .github/workflows/model_test_cpu.yml
- .github/workflows/model_test_hpu.yml
- .github/workflows/scripts/models/collect_log.sh
- setup.py
> bump version into v0.8

- evals/benchmark/stresscli/locust/gmc_chatqnafixed.py
Add benchmark script for GMC chatQnA workload
n/a
n/a
> Add GMC chatqna benchmark script

- README.md
- doc/platform-optimization/README.md
Add documentation that helps optimizing Kubernetes nodes for OPEA AI applications.
> doc: add Kubernetes platform-optimization README

- evals/metrics/ragas/ragas.py
add more ragas metrics for rag evaluation
for test case
{'answer_relevancy': 0.5402, 'faithfulness': 1.0000, 'answer_correctness': 0.7400, 'answer_similarity': 0.9598, 'context_precision': 1.0000, 'context_relevancy': 1.0000, 'context_recall': 0.5000}
> add more metrics for ragas.

- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/run.yaml
Support benchmark for docker deployment
`n/a`
None
Local test
> Support benchmark for docker deployment

- setup.py
bump release version into v1.0
> bump release version into v1.0

- evals/benchmark/benchmark.py
Fix microservice level benchmark issue
`n/a`
None
Local test
> Fix microservice level benchmark issue

- evals/benchmark/stresscli/locust/llmfixed.py
Align llm microservice parameters with end to end test
`n/a`
None
Local test
> Align llm microservice parameters with end to end test

- evals/benchmark/README.md
Update configuration in benchmark README.
Without these lines, user will meet with error when running benchmark
n/a
n/a
n/a
> Update configuration in benchmark README

- evals/benchmark/stresscli/locust/rerankingfixed.py
- evals/benchmark/stresscli/locust/rerankservefixed.py
Fixed the rerank benchmark script issue
The original request json is not well formatted, will cause "HTTPError 422 Client Error: Unprocessable Entity"
n/a
n/a
n/a
> Fix rerank benchmark script

- examples/FaqGen/README.md
Title was missing on FaqGen/README.md (PR #91)
> doc: add title to new FaqGen README

- evals/evaluation/rag_eval/examples/eval_multihop.py
fix error because the inputs of rag change
> fix issue because of ragas changes

- evals/evaluation/rag_eval/README.md
- evals/evaluation/rag_eval/examples/eval_multihop.py
update llm-as-judge doc for rag evaluation
> update llm-as-judge doc.

- examples/AudioQnA/README.md
- examples/AudioQnA/local_eval.py
- examples/AudioQnA/online_eval.py
- examples/AudioQnA/requirements.txt
add audioqna asr wer eval scripts
na
transformers
torch
datasets
evaluate
jiwer
soundfile
librosa
pydub
na
> add audioqna asr wer eval scripts

- evals/evaluation/rag_eval/README.md
update rag_eval readme according to the experience on K8s deployment
n/a
n/a
n/a
> update rag_eval readme

- evals/benchmark/benchmark.py
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/commands/report.py
* Supported to get benchmark reports in the python script.
* Refactored main func.
Usage:
```shell
python benchmark.py --report
```
or
```shell
from benchmark import benchmark
results = run_benchmark(report=True)
```
> [Benchmark] Get benchmark reports.

- evals/benchmark/grafana/README.md
- evals/benchmark/grafana/gaudi_grafana.json
Add a new Grafana dashboard JSON file for monitoring the Gaudi metrics in k8s cluster.
N/A
N/A
Local tests.
> add the grafana dashboard json file for Gaudi metrics

- evals/benchmark/benchmark.py
- evals/benchmark/benchmark.yaml
- evals/benchmark/utils.py
Allow user to specify different namespace for benchmarking.
> Add namespace support for k8s benchmarking

- evals/evaluation/deepeval/README.md
- evals/evaluation/deepeval/models/endpoint_models.py
- requirements.txt
- tests/test_answer_relevancy.py
- tests/test_bias.py
- tests/test_hallucination.py
- tests/test_toxicity.py
customize model to support tgi/vllm endpoint for evaluation with deepeval metrics
> integrate deepeval metric with remote endpoint, like tgi server.

- evals/evaluation/bigcode_evaluation_harness/api_evaluator.py
Signed-off-by: Yao, Qing <qing.yao@intel.com>
(cherry picked from commit f0ee48ec57783f0e7156f4d43294d1486ee1e5b3)
Control the concurrent number of requests in codegen acc test.
`n/a`.
> Control the concurrent number of requests in codegen acc test.

- evals/benchmark/stresscli/locust/aistress.py
Force export LLM_Model environment variable
`n/a`
None
Local test
> Force export LLM_Model environment variable

- evals/benchmark/stresscli/locust/tokenresponse.py
Fix llm output token length issue
`n/a`
None
Local test
> Fix llm output token length issue

- evals/benchmark/stresscli/locust/tokenresponse.py
This reverts commit 99ef3255763770eaee30222fbecc61e1dce2c5fd.
The summary of the proposed changes as long as the relevant motivation and context.
> Revert "Fix llm output token length issue (#175)"

- requirements.txt
fix ragas version bug to align with ragas code
> fix ragas version bug

- evals/evaluation/rag_eval/evaluator.py
- evals/evaluation/rag_eval/examples/eval_multihop.py
for no wrapper ChatQnA service, there is no wrapper `embedding_endpoint`, so replace it with `tei_embedding_endpoint`.
> update embedding endpoint for no wrapper.

- .github/workflows/check-online-doc-build.yml
opt CI to skip none MD and RST files
> opt CI to skip none MD and RST files

- .github/CODEOWNERS
- .github/license_template.txt
Change license template 2024 to 2025
> Change license template from 2024 to 2025

- evals/__init__.py
- evals/benchmark/__init__.py
- evals/version.py
- setup.py
1. Add benchmark code into opea-eval binary. 
2. Bump release version into v1.2. 
> Add benchmark code into opea-eval binary

- evals/benchmark/stresscli/README.md
- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/commands/report.py
- evals/benchmark/stresscli/commands/utilization.py
- evals/benchmark/stresscli/requirements.txt
- evals/benchmark/stresscli/run.yaml
The summary of the proposed changes as long as the relevant motivation and context.
Integrate memory bendwidth exporter and stresscli to support collection and reporting of memory bandwidth, cpu, mem metrics.
Get the data from multiple endpoints of the memory bandwidth exporter, and save the original data and processed data of each metric into csv files.
Already tested on GNR.
> Integrate with memory bandwidth exporter to support collection and reporting of memory bandwidth, cpu, mem metrics.

- setup.py
Add the missed file in release package for example benchmark. 
> Add the missed file in release package

- evals/benchmark/stresscli/commands/load_test.py
- evals/benchmark/stresscli/locust/chatqna_qlist_pubmed.py
- evals/benchmark/stresscli/locust/tokenresponse.py
1. Use input `processes` instead of dynamic processes. 
2. Fix pubmed data path. 
3. Fix benchmark duration calculate. 
> Fix performance benchmark with pubmed

- .github/code_spell_ignore.txt
- pyproject.toml
Add code spell ignore
https://github.com/opea-project/GenAIEval/pull/241
> Add code spell ignore

- evals/benchmark/stresscli/locust/aistress.py
- evals/benchmark/stresscli/locust/tokenresponse.py
Initialize the tokenizer only once.
No hang issues.
N/A
✔ user 128/256/512
✔ query 512/1024
> [Enhance] Initialize the tokenizer only once

- .pre-commit-config.yaml
exclude evals/evaluation/HELMET in code format check
> exclude evals/evaluation/HELMET in code format check

- doc/platform-optimization/README.md
Update platform optimization documentation with recommendations on CPU inference.
> Add recommendations to platform optimization documentation

- evals/version.py
> Bump version into v1.3

- evals/benchmark/stresscli/commands/metrics_util.py
Add new vLLM serving metrics:
vllm-service_average_queue_time
vllm-service_average_prefill_time
vllm-service_average_decode_time
vllm-service_average_prompt_tokens
vllm-service_average_generation_tokens
n/a
> [vLLM]Enhance vLLM metrics collection

- docker/benchmark.dockerfile
Correct the benchmark Dockerfile repo
#271 
Follow the README and benchmark by docker container
https://github.com/opea-project/GenAIEval/blob/main/docker/README.md
> Correct the benchmark Dockerfile repo

- evals/benchmark/stresscli/commands/metrics_docker.py
Retrieve metrics from container IP and port instead of container name and mapped port
Fix: #275
#275 
Workload chatQnA  with docker compose.
change benchmark.yaml to correct settings
Run benchmark outside container(baremetal)
metrics collection will be success
> [Metrics] Fix Collect metrics failed from baremetal(#275)
